### ISSUE TITLE
Bidirectional data replication not happening in strimzi mirrormaker2

### ISSUE THREAD

**Issue by Raju-kf** [strimzi/mirror-maker-2-extensions#9]
Hello, I am using Strimzi MirrorMaker2 for replicating data between two kafka clusters. Bidirectional data replication is not happening in my case. I'm using strimzi operator 0.26 and kafka 2.8.0. Please let me know any special configuration required to enable bidirectional data replication in following mirrormaker2 configurations.

->From source to target cluster able to replicated topics and data but from target to source data replication is not happening.
->Topics are getting duplicated in both kafka clusters.
-> How can we configure data flow policies from A -> B clusters, any example configuration file is there.

Providing my mirrormaker.yaml file
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
 name: my-mirror-maker-2
spec:
 version: 2.8.0
 replicas: 1
 connectCluster: "my-target-cluster"
 clusters:
 - alias: "my-source-cluster"
   bootstrapServers: xxxx:30056
   tls:
     trustedCertificates:
       - secretName: my-cluster-cluster-ca-cert
         certificate: ca.crt
 - alias: "my-target-cluster"
   bootstrapServers: xxxx:30054
   tls:
     trustedCertificates:
       - secretName: my-target-cluster-cluster-ca-cert
         certificate: ca.crt
   config:
     config.storage.replication.factor: -1
     offset.storage.replication.factor: -1
     status.storage.replication.factor: -1
 mirrors:
 - sourceCluster: "my-source-cluster"
   targetCluster: "my-target-cluster"
   sourceConnector:
     config:
       replication.factor: 1
       offset-syncs.topic.replication.factor: 1
       sync.topic.acls.enabled: "false"
       refresh.topics.interval.seconds: 5
   heartbeatConnector:
     config:
       heartbeats.topic.replication.factor: 1
   checkpointConnector:
     config:
       checkpoints.topic.replication.factor: 1
   topicsPattern: ".*"
   groupsPattern: ".*"
 resources:
   requests:
     cpu: 200m
     memory: 2Gi
   limits:
     cpu: 250m
     memory: 2Gi
```

Topics list from source kafka c;usters:

[kafka@my-cluster-kafka-0 kafka]$ ./bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
__consumer_offsets
__strimzi-topic-operator-kstreams-topic-store-changelog
__strimzi_store_topic
cluster-c1
cluster-c1-1
heartbeats
mirrormaker2-cluster-configs
mirrormaker2-cluster-offsets
mirrormaker2-cluster-status
mm2-offset-syncs.my-target-cluster.internal
my-cluster-connect-cluster-configs
my-cluster-connect-cluster-offsets
my-cluster-connect-cluster-status
my-source-cluster.checkpoints.internal
my-source-cluster.cluster-c2
my-source-cluster.heartbeats
my-source-cluster.mirrormaker2-cluster-configs
my-source-cluster.mirrormaker2-cluster-offsets
my-source-cluster.mirrormaker2-cluster-status
my-source-cluster.my-source-cluster.cluster-c1
my-source-cluster.my-source-cluster.cluster-c1-1
my-source-cluster.my-source-cluster.heartbeats
my-source-cluster.my-source-cluster.mirrormaker2-cluster-configs
my-source-cluster.my-source-cluster.mirrormaker2-cluster-offsets
my-source-cluster.my-source-cluster.mirrormaker2-cluster-status
my-source-cluster.my-source-cluster.my-cluster-connect-cluster-configs
my-source-cluster.my-source-cluster.my-cluster-connect-cluster-offsets
my-source-cluster.my-source-cluster.my-cluster-connect-cluster-status
my-source-cluster.my-source-cluster.my-source-cluster.cluster-c2
my-source-cluster.my-source-cluster.my-source-cluster.heartbeats
my-source-cluster.my-source-cluster.my-source-cluster.mirrormaker2-cluster-configs
my-source-cluster.my-source-cluster.my-source-cluster.mirrormaker2-cluster-offsets
my-source-cluster.my-source-cluster.my-source-cluster.mirrormaker2-cluster-status
my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.cluster-c1
my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.cluster-c1-1
